import slugify from '../utils/slugify'

export default {
  title: "Journal",
  name: 'journal',
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Images Top",
      description: "If this is toggled the images will appear at the top rather than the sidebar allowing more room for content",
      name: "imagesTop",
      type: "boolean"
    },
    {
      title: "External URL",
      description: "If entered, this journal teaser will link off to an external site rather than internally within the website.'",
      name: "externalUrl",
      type: "string"
    },
    {
      title: "Publish Date",
      description: "Press the button to the right to pick a date.",
      name: "date",
      type: "date",
      options: {
        dateFormat: "MMMM Do YYYY",
      },
      validation: Rule => Rule.required()
    },
    {
      title: "Meta Type",
      description: "A short meta description of what this journal entry is about, eg: 'Project Update'",
      name: "metaType",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: 'Teaser Image Layout',
      name: 'layout',
      type: 'string',
      options: {
        list: [
          {title: 'Square', value: 'square'},
          {title: 'Landscape', value: 'landscape'},
          {title: 'Portrait', value: 'portrait'},
          {title: 'Small Square', value: 'small-square'}
        ],
        layout: 'dropdown'
      }
    },
    {
      title: 'Images',
      name: 'images',
      type: 'array',
      of: [
        {
          name: 'image',
          type: 'image',
          description: "The image gallery for this journal entry, the amount will define the type of layout used.",
          title: 'Image',
          options: {
            hotspot: true,
          },
          fields: [
            {
              name: 'alt',
              type: 'string',
              title: 'Alternative text',
            },
          ],
        },
      ],
      options: {
        layout: 'grid',
      },
    },
    {
      title: 'Content',
      name: 'content',
      type: 'array', 
      of: [{type: 'block'}]
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ]
}